### ISSUE TITLE
Introduce the concept of Gamification on the bees example

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#357]
* we introduced the general webhook concept a few years back into galaxy
* this has enabled custom modifications to Galaxy UI without changing Galaxy source code and make maintenance of those changes easier. It is a plugin concept for Galaxy UI.
* this is what is powering the much loved XKCD or PhD comics for example - but this was just the first step ...
* Today we are proud to introduce you an extension that helps our ecology community to train their machine learning model to classify bees into male and female
* technical details how this works, what will be done with the data, how does it help, why is it good to help ... --> motivation
* small paragraph about "how to create new plugins of this kind" ...
* Adding some example images

**Comment by yvanlebras** [comment]
Wouhahou! Nice. MAybe I would propose "to annotate existing datasets classifying hoverflies into male and female so this information can be used in further data treatment for example to train future machine learning models" instead of "to train their machine learning model to classify bees into male and female"

I have to write something for the motivation part and come back to you

**Comment by bgruening** [comment]
My list above was just ideas that could be in such an announcement. If you have time to generate a first pass, awesome.

**Comment by bgruening** [comment]
This link should also be included I guess :) 
https://usegalaxy.eu/gapars-experiment/

**Comment by beatrizserrano** [comment]
I have some minor suggestions:

* Is the submit button really needed? Only picking the option could be enough to submit automatically.
* I would replace "Cannot See" by "Not sure" because sometimes one can see but can't decide.
* Mark the borders of the 5 options or perhaps just align the labels: at first I thought that there were only 3 options, I ignored completely "Likely male" and "Likely female". Not even sure if the "Likely" options are needed either, I hardly ever use them.

It's quite cool, thanks :)

**Comment by yvanlebras** [comment]
Thank you ! Here is a first draft for a EU news https://github.com/galaxyecology/communication/blob/master/2020-01-galaxyeu-news/index.md
